defaults:
  - _self_
  - model: KANet
    
training:
  epochs: 20
  optimizer: adamw
  log: False
  size: 100000
  learning_rate: 0.001
  tag: None
  name: None
  decay: 0
  dataset: Fashion-MNIST
  label_smoothing: 0